import Foundation

/// Classifications for `isMeta=true` user-line content. Borrows ideas from
/// `claude-devtools/src/shared/utils/contentSanitizer.ts` (the Built-in vs.
/// Skill ordering distinction, the `<local-command-*>` family) — implemented
/// in Swift idioms with no regex.
///
/// Each case carries the **extracted** body (the substance between
/// structural tags), not the raw wrapped form. Downstream routing (Phase B
/// snapshot derivation) decides whether the body renders inline or surfaces
/// a clickable title link based on content size and the section's caps.
enum ClaudeMetaContent: Equatable {
    /// `<command-name>/foo</command-name><command-args>bar</command-args>`
    /// or its skill-flavoured form
    /// `<command-message>foo</command-message><command-name>/foo</command-name>`.
    /// `name` is the slash without the leading `/`; `args` may be nil.
    case slashCommandInput(name: String, args: String?)

    /// `<local-command-stdout>...</local-command-stdout>` — or `stderr` form.
    /// `body` is the inner text; `isStderr` distinguishes the source stream.
    case slashCommandOutput(body: String, isStderr: Bool)

    /// `<local-command-caveat>...</local-command-caveat>` — the short
    /// "Caveat: The messages below were generated by..." preface that
    /// surrounds slash-command stdout. Body is the inner text.
    case localCommandCaveat(body: String)

    /// `<system-reminder>...</system-reminder>` — system-emitted reminder
    /// (session name change, hook-emitted notice, etc.). Body is the inner
    /// text.
    case systemReminder(body: String)

    /// `Base directory for this skill: <path>` followed by `# <SkillName>`
    /// followed by the skill body. `name` is the parsed `# Heading`,
    /// `basePath` the parsed directory, `body` is the full markdown after
    /// the prefix.
    case skillInvocation(name: String, basePath: String, body: String)

    /// `## Context Usage\n\n**Model:** …` — auto-emitted recap-style
    /// telemetry block. Body is the full text.
    case contextUsage(body: String)

    /// `Continue from where you left off.` — auto-resume marker. No body.
    case continueResume

    /// Anything else: unknown / freeform. Body is the raw content; the
    /// router decides routing by content size.
    case unknown(body: String)
}

enum ClaudeContentDetector {
    /// Extract the inner text of a tag pair if `text` opens with `<tagName>`
    /// and contains the matching closing tag. Returns nil otherwise.
    static func extractTag(_ text: String, tag: String) -> String? {
        let openTag = "<\(tag)>"
        let closeTag = "</\(tag)>"
        guard text.hasPrefix(openTag) else { return nil }
        guard let openEnd = text.range(of: openTag),
              let closeStart = text.range(of: closeTag, range: openEnd.upperBound..<text.endIndex) else {
            return nil
        }
        return String(text[openEnd.upperBound..<closeStart.lowerBound])
    }

    /// Scan for `<tagName>...</tagName>` anywhere in `text` (not just at the
    /// start). Used for the skill-flavour command pattern where
    /// `<command-message>` precedes `<command-name>`.
    static func scanTag(_ text: String, tag: String) -> String? {
        let openTag = "<\(tag)>"
        let closeTag = "</\(tag)>"
        guard let openStart = text.range(of: openTag) else { return nil }
        guard let closeStart = text.range(of: closeTag, range: openStart.upperBound..<text.endIndex) else {
            return nil
        }
        return String(text[openStart.upperBound..<closeStart.lowerBound])
    }

    /// Classify `text` (the extracted body of a `user` line whose
    /// `isMeta == true`). Returns `.unknown(body:)` for anything that
    /// doesn't structurally match a known wrapper.
    static func classify(_ text: String) -> ClaudeMetaContent {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)

        // Slash-command output (stdout/stderr).
        if let body = extractTag(trimmed, tag: "local-command-stdout") {
            return .slashCommandOutput(body: body.trimmingCharacters(in: .whitespacesAndNewlines), isStderr: false)
        }
        if let body = extractTag(trimmed, tag: "local-command-stderr") {
            return .slashCommandOutput(body: body.trimmingCharacters(in: .whitespacesAndNewlines), isStderr: true)
        }

        // Slash-command caveat wrapper.
        if let body = extractTag(trimmed, tag: "local-command-caveat") {
            return .localCommandCaveat(body: body.trimmingCharacters(in: .whitespacesAndNewlines))
        }

        // System reminder.
        if let body = extractTag(trimmed, tag: "system-reminder") {
            return .systemReminder(body: body.trimmingCharacters(in: .whitespacesAndNewlines))
        }

        // Slash-command input — two orderings:
        //   built-in: <command-name>/foo</command-name><command-args>bar</command-args>
        //   skill:    <command-message>foo</command-message><command-name>/foo</command-name>
        if trimmed.hasPrefix("<command-name>") || trimmed.hasPrefix("<command-message>") {
            // Prefer command-name's slash-token as the canonical name; fall
            // back to command-message when the line opens with it (skill flavour).
            let slashName: String? = scanTag(trimmed, tag: "command-name").map { token in
                token.hasPrefix("/") ? String(token.dropFirst()) : token
            }
            let messageName = scanTag(trimmed, tag: "command-message")
            let args = scanTag(trimmed, tag: "command-args")?.trimmingCharacters(in: .whitespacesAndNewlines)
            let resolvedName = slashName?.isEmpty == false
                ? slashName!
                : (messageName ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            return .slashCommandInput(
                name: resolvedName,
                args: (args?.isEmpty == false) ? args : nil
            )
        }

        // Skill invocation. Lead line is "Base directory for this skill: <path>".
        if trimmed.hasPrefix(skillBaseDirPrefix) {
            return classifySkillInvocation(trimmed)
        }

        // Context-usage recap header.
        if trimmed.hasPrefix(contextUsagePrefix) {
            return .contextUsage(body: trimmed)
        }

        // Resume marker.
        if trimmed == continueResumeMarker {
            return .continueResume
        }

        return .unknown(body: trimmed)
    }

    // MARK: - Internal helpers

    private static let skillBaseDirPrefix = "Base directory for this skill: "
    private static let contextUsagePrefix = "## Context Usage"
    private static let continueResumeMarker = "Continue from where you left off."

    private static func classifySkillInvocation(_ text: String) -> ClaudeMetaContent {
        // First line: "Base directory for this skill: <path>"
        // Then: blank line, then "# <Skill Name>", then body.
        guard let firstNewline = text.firstIndex(of: "\n") else {
            // Degenerate one-liner. Treat the path as the name.
            let path = String(text.dropFirst(skillBaseDirPrefix.count))
            return .skillInvocation(name: path, basePath: path, body: "")
        }
        let basePath = String(text[text.index(text.startIndex, offsetBy: skillBaseDirPrefix.count)..<firstNewline])
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let remainder = String(text[text.index(after: firstNewline)...])
            .trimmingCharacters(in: .whitespacesAndNewlines)

        // Look for the first `# Heading` line for the skill name.
        var skillName: String? = nil
        for rawLine in remainder.components(separatedBy: "\n") {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.hasPrefix("# ") {
                skillName = String(line.dropFirst(2)).trimmingCharacters(in: .whitespaces)
                break
            }
            if !line.isEmpty { break }
        }

        // Fall back to the last path component.
        let resolvedName = skillName?.isEmpty == false
            ? skillName!
            : (basePath as NSString).lastPathComponent

        return .skillInvocation(name: resolvedName, basePath: basePath, body: remainder)
    }
}
